### PR TITLE
chore: mark native image checks as required

### PR DESCRIPTION
**Pull request by mpeddada1**

### CODE REVIEW

**Review by losalex — COMMENTED** [review]
I think we cannot enable those checks to be mandatory by default unless we add missing integration tests

**Comment by mpeddada1** [comment]
Currently running into: 
```
com.google.cloud.logging.LoggingException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute' of service 'logging.googleapis.com' for consumer 'project_number:1016721519174'.
```

**Comment by losalex** [comment]
> Currently running into:
> 
> ```
> com.google.cloud.logging.LoggingException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute' of service 'logging.googleapis.com' for consumer 'project_number:1016721519174'.
> ```

We need to wait and retry - unfortunately we must make sure that step "Kokoro - Test: Java 17 GraalVM Native Image" is succeeding

**Comment by mpeddada1** [comment]
Got it, thanks @losalex. Looks like rerunning the jobs did the trick.

**Review by losalex — APPROVED** [review]

**Pull request merged**
