### PR TITLE
feat: add support for k8s_container resource type

### LINKED ISSUE #206: add support for k8s_container resource type
When setting the k8s_container resource type in logbak.xml,it doesn't fill in any of the resource labels associated with it.

```logback.xml```

```
<configuration>
    <appender name="CLOUD" class="com.google.cloud.logging.logback.LoggingAppender">
        <!-- Optional : filter logs at or above a level -->
        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>INFO</level>
        </filter>
        <log>my-log-test</log> <!-- Optional : default java.log -->
        <resourceType>k8s_container</resourceType>
        <flushLevel>WARN</flushLevel> <!-- Optional : default ERROR -->
    </appender>
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>
    <root level="debug">
        <appender-ref ref="CLOUD"/>
        <appender-ref ref="STDOUT"/>
    </root>
</configuration>
```
output:
```
resource: {
  type: "k8s_container"
  labels: {
    cluster_name: ""
    pod_name: ""
    container_name: ""
    namespace_name: ""
    location: ""
    project_id: "XXX"
   }
}
```

### PR DESCRIPTION
**Pull request by suraj-qlogic**
Fixes #206

### CODE REVIEW

**Comment by suraj-qlogic** [comment]
@simonz130 , @chingor13  PTAL

**Comment by jeremyvdw** [comment]
Hi there, any chance of having this merged anytime soon? Thanks

**Comment by twistedpair** [comment]
Any chance of merging this soon? Fluentd records these values by default in GKE, but the [GCP Logback](https://github.com/googleapis/java-logging-logback) appender doesn't because of this lack of metadata. This PR will fix that problem and be very helpful to our ability to query this log data.

**Comment by suraj-qlogic** [comment]
@simonz130 ,gentle ping

**Review by simonz130 — APPROVED** [review]

**Pull request merged**
